# Generated by Django 5.2.4 on 2025-08-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='trx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
