# Generated by Django 5.2.4 on 2025-08-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_rename_price_booking_unit_price_booking_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='unit_price',
            new_name='price',
        ),
    ]
