# Generated by Django 5.2.4 on 2025-08-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_chatmessage_deleted_for_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='deleted_for_recipient',
            new_name='deleted_by_receiver',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='deleted_for_sender',
            new_name='deleted_by_sender',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='is_read',
            new_name='seen',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ChatUserStatus',
        ),
    ]
