# Generated by Django 5.2.4 on 2025-08-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='seen',
            new_name='deleted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
    ]
