# Generated by Django 5.2.4 on 2025-08-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_alter_message_options_rename_message_message_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='sent', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
    ]
