# Generated by Django 5.2.4 on 2025-08-16 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0011_alter_message_options_remove_message_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
    ]
