# Generated by Django 5.2.4 on 2025-08-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0012_remove_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='receivermessage',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sendermessage',
            field=models.CharField(blank=True, null=True),
        ),
    ]
