# Generated by Django 5.2.4 on 2025-08-16 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0013_message_message_message_receivermessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receivermessage',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sendermessage',
        ),
    ]
